### ISSUE TITLE
Paper has NoSuchMethodError with net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.i()Ljava/util/EnumSet

### ISSUE THREAD

**Issue by xcreator** [PaperMC/Paper#3473]
### What behaviour is expected:
PathfinderGoal System working well with Spigot 1.15.2
but Paper is not.

### What behaviour is observed:
[05:04:48] [Server thread/WARN]: [WonderEssentials] Task #1719 for WonderEssentials v1.0 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_15_R1.PathfinderGoalWrapped.i()Ljava/util/EnumSet;
	at me.WonderNPC.WonderNPC.setNpcAI(WonderNPC.java:1374) ~[?:?]
	at me.WonderNPC.WonderNPC.spawnNewNpc(WonderNPC.java:1248) ~[?:?]
	at me.WonderNPC.WonderNPC.access$6(WonderNPC.java:1238) ~[?:?]
	at me.WonderNPC.WonderNPC$6.run(WonderNPC.java:380) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-324]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-324]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-324]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-324]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-324]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-324]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

### Steps/models to reproduce:
I don't know what this line talking about.

### Plugin list:
dynmap, Vault, VoxelSniper, ProtocolLib, newPaintingSwitch, LibsDisguises, WorldEdit,
and my own plugins : WonderPlugin, WonderRegion, WonderMap, WonderEssentials

### Paper build number:
paper-324 and paper-325

### Anything else:
I don't understand paper's API algorithm.
isn't it same with spigot 1.15.2 API?
I don't sure... but why paper printed NoSuchMethodError?

**Comment by A248** [comment]
> I don't understand paper's API algorithm.
> isn't it same with spigot 1.15.2 API?

The *API* is the same. But some plugins are naughty and use NMS. Hence:
https://github.com/PaperMC/Paper/blob/36f34f01c09652b3a55008000302114570473953/Spigot-Server-Patches/0464-Remove-streams-from-Mob-AI-System.patch#L246
The patch should probably be modified to re-add this method. However, the plugin still won't work (you just won't receive an error) unless it specifically adds support for Paper.

**Comment by aikar** [comment]
The code you are trying to touch is not API. internals are subject to change like this, and this is the risk you take with using NMS.

The plugin will need to detect if the server is paper and use our version instead, or ideally, use our proper API we have included that lets you access this system without using NMS in first place:

https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0202-Add-Mob-Goal-API.patch
