### ISSUE TITLE
The Plugin AdvanedGUI throws an error

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#5913]
### Expected behavior

An issue on creating

### Observed/Actual behavior

The plugin work fine in current Spigot 1.17
in Paperon Objet creating it throws this error

```
[21:17:01] [Server thread/INFO]: Cloude_Lecaw issued server command: /advancedgui place magie
[21:17:10] [Craft Scheduler Thread - 83/WARN]: [AdvancedGUI] Plugin AdvancedGUI v2.0.5 generated an exception while executing task 34363
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/it/unimi/dsi/fastutil/ints/Int2ObjectMap
	at com.comphenix.protocol.reflect.instances.DefaultInstances.lambda$static$0(DefaultInstances.java:57) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefaultInternal(DefaultInstances.java:288) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefault(DefaultInstances.java:195) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.create(DefaultInstances.java:363) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:59) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:121) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.sendRenderData(GuiInstance.java:192) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$null$0(GuiInstance.java:168) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$startRendering$1(GuiInstance.java:142) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.ints.Int2ObjectMap
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 16 more
[21:17:10] [Craft Scheduler Thread - 84/WARN]: [AdvancedGUI] Plugin AdvancedGUI v2.0.5 generated an exception while executing task 34363
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/it/unimi/dsi/fastutil/ints/Int2ObjectMap
	at com.comphenix.protocol.reflect.instances.DefaultInstances.lambda$static$0(DefaultInstances.java:57) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefaultInternal(DefaultInstances.java:288) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefault(DefaultInstances.java:195) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.create(DefaultInstances.java:363) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:59) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:121) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.sendRenderData(GuiInstance.java:192) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$null$0(GuiInstance.java:168) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$startRendering$1(GuiInstance.java:142) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:17:10] [Craft Scheduler Thread - 80/WARN]: [AdvancedGUI] Plugin AdvancedGUI v2.0.5 generated an exception while executing task 34363
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/libs/it/unimi/dsi/fastutil/ints/Int2ObjectMap
	at com.comphenix.protocol.reflect.instances.DefaultInstances.lambda$static$0(DefaultInstances.java:57) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefaultInternal(DefaultInstances.java:288) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.getDefault(DefaultInstances.java:195) ~[?:?]
	at com.comphenix.protocol.reflect.instances.DefaultInstances.create(DefaultInstances.java:363) ~[?:?]
	at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:59) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:121) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.sendRenderData(GuiInstance.java:192) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$null$0(GuiInstance.java:168) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at me.leoko.advancedgui.utils.GuiInstance.lambda$startRendering$1(GuiInstance.java:142) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"33d6b6f"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Steps/models to reproduce

Great a GUI with Adanced GUI

### Plugin list

AvancedGUI
Protocollib

### Paper version

Build 15 of 1.17 Paper

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Fejm** [comment]
Report this to plugin author.

**Comment by e-im** [comment]
~~Tracked here: https://github.com/PaperMC/paperweight/issues/24~~ my mistake, this isn't a mapping issue at all just that spigot relocates fastutil. see below comment

**Comment by MiniDigger** [comment]
Fixed by protocol here https://github.com/dmulloy2/ProtocolLib/commit/1c2bc274dd8b70ec141ce7242a46ad31c319f91b
Not a paper issue

**Comment by CloudeLecaw** [comment]
Solved with updating to latest Protocolib. Thanks for this info.. i was using 507 that was released at the beginning of 1.17 :3  updated now to 520.
