### PR TITLE
Rewrite Adventure Book calls to BookMeta

### LINKED ISSUE #14030: NoSuchMethodError for (removed adventure) Book interface's setter
### Expected behavior

When compiling against Paper 26.1.2 (or before) using the BookMeta#pages setter methods should also work on a 26.2 server since it is api.

### Observed/Actual behavior

[17:35:25 INFO]: TheosRee issued server command: /bookmetatest getter
[17:35:29 INFO]: TheosRee issued server command: /bookmetatest setterArray
[17:35:29 ERROR]: Command exception: /bookmetatest setterArray
java.lang.NoSuchMethodError: 'net.kyori.adventure.inventory.Book org.bukkit.inventory.meta.BookMeta.pages(net.kyori.adventure.text.Component[])'
        at TR-Test.jar//de.ree.theos.Test$1.execute(Test.java:69) ~[?:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-26.2.jar:26.2-20-2c0341f]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-26.2.jar:26.2-20-2c0341f]
[…more stack trace]
[17:35:33 INFO]: TheosRee issued server command: /bookmetatest setterList
[17:35:33 ERROR]: Command exception: /bookmetatest setterList
java.lang.NoSuchMethodError: 'net.kyori.adventure.inventory.Book org.bukkit.inventory.meta.BookMeta.pages(java.util.List)'
        at TR-Test.jar//de.ree.theos.Test$1.execute(Test.java:68) ~[?:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-26.2.jar:26.2-20-2c0341f]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-26.2.jar:26.2-20-2c0341f]
[…more stack trace]

### Steps/models to reproduce

```java
getServer().getCommandMap().register("ignored", new Command("bookmetatest") {
    @Override
    public boolean execute(final CommandSender sender, final String label, final String[] args) {
        final ItemStack book = ItemStack.of(Material.WRITTEN_BOOK);
        final BookMeta meta = (BookMeta) book.getItemMeta();
        switch (args[0]) {
            case "getter" -> meta.pages();
            case "setterList" -> meta.pages(List.of());
            case "setterArray" -> meta.pages(Component.empty());
        }
        return true;
    }
});
```

targetting the following version or any before down to like 1.18
```xml
<dependency>
    <groupId>io.papermc.paper</groupId>
    <artifactId>paper-api</artifactId>
    <version>26.1.2.build.72.stable</version>
    <scope>provided</scope>
</dependency>
```

### Plugin and Datapack List

The test plugin

### Paper version

This server is running Paper version 26.2-20-dev/26.2@2c0341f (2026-06-17T19:31:24Z) (Implementing API version 26.2.build.20-alpha)
You are 28 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 26.2-19-80d1098 (MC: 26.2)

This server is running Paper version 26.2-48-main@87c4d42 (2026-07-04T14:09:05Z) (Implementing API version 26.2.build.48-alpha)
You are running the latest version
Previous version: 26.2-20-2c0341f (MC: 26.2)

### Other

it is since https://fill-ui.papermc.io/projects/paper/version/26.2?build=20 with
https://github.com/PaperMC/Paper/commit/2c0341f9f291cba995c5293122bf888138427d17#diff-e0871225f23971b54756b88cbe0d16e1aa4995d857a5d0c56aa7c18e904f647eL17-R20
I asked on Discord and it was suggested to open the issue in Paper instead Adventure because it is an Item-/BookMeta issue and should probably get an `api-version` rewrite.

### LINKED ISSUE #14135: BookMeta#asBook yields not full book
### Expected behavior

Using the `asBook` method on 26.2 should provide the same result as on 1.21.8/26.1.2.

Image

### Observed/Actual behavior

The given book is yielding incomplete and wrong (legacy color codes instead real colors) data.

Image

### Steps/models to reproduce

1.21.8/26.1.2 code:
```java
final Component deserialized = MiniMessage.miniMessage().deserialize("<rainbow><bold>Really");
for (final Material material : new Material[]{Material.WRITTEN_BOOK, Material.WRITABLE_BOOK}) {
    final ItemStack book = ItemStack.of(material);
    final BookMeta bookMeta = (BookMeta) book.getItemMeta();
    final Book adventure = bookMeta.title(deserialized).author(deserialized).pages(deserialized);
    sender.sendMessage(adventure.title());
    sender.sendMessage(adventure.author());
    sender.sendMessage(join(JoinConfiguration.commas(true), adventure.pages()));
    book.setItemMeta(bookMeta);
}
```

26.2 code: I just get the Book now in a new line as the Interface is no longer in the return method.
```java
final Component deserialized = MiniMessage.miniMessage().deserialize("<rainbow><bold>Really");
for (final Material material : new Material[]{Material.WRITTEN_BOOK, Material.WRITABLE_BOOK}) {
    final ItemStack book = ItemStack.of(material);
    final BookMeta bookMeta = (BookMeta) book.getItemMeta();
 // final Book adventure = bookMeta.title(deserialized).author(deserialized).pages(deserialized);
    bookMeta.title(deserialized).author(deserialized).pages(deserialized);
    final Book adventure = bookMeta.asBook();
    sender.sendMessage(adventure.title());
    sender.sendMessage(adventure.author());
    sender.sendMessage(join(JoinConfiguration.commas(true), adventure.pages()));
    book.setItemMeta(bookMeta);
}
```

### Plugin and Datapack List

Just the test plugin's code as described above.
The code is wrapped in the following command:
```java
getServer().getCommandMap().register("ignored", new Command("bookmetatest") {
    @Override
    public boolean execute(final CommandSender sender, final String commandLabel, final String[] args) {
        if (args.length == 1) {
            // code
        }
    }
}
```

### Paper version

[22:57:20 INFO]: Checking version, please wait...
[22:57:20 INFO]: This server is running Paper version 26.2-92-main@0a99345 (2026-08-02T20:33:44Z) (Implementing API version 26.2.build.92-stable)
You are running the latest version

and 

[20:58:37 INFO]: Checking version, please wait...
[20:58:37 ERROR]: [PaperVersionFetcher] Error while parsing version
…
[20:58:37 INFO]: This server is running Paper version 1.21.8-60-main@29c8822 (2025-09-06T21:49:13Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)
Error obtaining version information

### Other

There is already a fix in #14081 which yields the following colors, with the only difference being the as string stored title and author in a slightly different brightness.

Image

### PR DESCRIPTION
**Pull request by TheosRee**
Fixes #14030 with re-routing the `pages` setter calls to the Book to the BookMeta and then returning the new `asBook`, rightfully returing an adventure Book instance to work with.

In the process of testing the result I discovered and fixed #14135, which also got broken in the adventure 5 update process. I decided to fix both in the same PR since both issues break the expected result/usage of the methods.

### CODE REVIEW

**Comment by TheosRee** [comment]
I would like to know if the version check should be dropped (the method with a different signature can't be compiled against 26.2 anyways) and if the added code should be at the start or end of the method. I tried to figure it from the changes but it did not lead me to a fixed result.

I also hope that the removal of the remnant method is ok and if I should also remove the methods which now just call super.

**Comment by masmc05** [comment]
Wouldn't this break if 
1. it was used in a chain, so `bookMeta.method1().method2()` would have had a Book#method2() signature and not a BookMeta#method2(), method1's rewrite to return bookmeta instead of book will break method2
2. The result is passed into a non api method that accepts only an adventure book, and it would result in some error as book meta isn't a book anymore

**Comment by TheosRee** [comment]
1. Yes, any chained call after one of the `pages` setter methods will break with a `java.lang.IncompatibleClassChangeError: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book`. When I am correct that can't be fixed easily because that is an independent call to a different interface? Changing that would also rewrite all "legit" calls to adventure books. Having that method at the end of the chain works however since all other methods (author and title) return the BookMeta and not the Book.
2. That is nothing that I thought of but like my thoughts to 1.: With the `openBook` method on the player that is kinda legit, but you could also pass the item stack when you work with meta anyways - without you would just work with a Book directly?

<details> 
<summary>Here is my test with the branch:</summary>

```java
@Override
public boolean execute(final CommandSender sender, final String commandLabel, final String[] args) {
    final ItemStack book = ItemStack.of(Material.WRITTEN_BOOK);
    final BookMeta meta = (BookMeta) book.getItemMeta();
    eval("getter", () -> meta.pages());
    eval("workingChain", () -> meta.author(Component.empty()).title(Component.empty()).pages(List.of()));
    eval("setterL", () -> meta.pages(List.of()));
    eval("setterL2", () -> meta.pages(List.of()).pages());
    eval("setterA", () -> meta.pages(Component.empty()));
    eval("setterA2", () -> meta.pages(Component.empty()).author());
    eval("doubleSetter", () -> meta.pages(Component.empty()).pages(Component.empty()));
    eval("doubleSetter2", () -> meta.pages(List.of()).pages(List.of()));
    eval("title", () -> meta.title(Component.empty()).pages(List.of()));
    eval("title2", () -> meta.title(Component.empty()).pages(List.of()).title());
    eval("author", () -> meta.author(Component.empty()).pages(List.of()));
    eval("author2", () -> meta.author(Component.empty()).pages(List.of()).author());
    sender.sendMessage(Component.text("Executed book meta test"));
    return true;
}

private void eval(final String name, final Runnable runnable) {
    try {
        runnable.run();
        getLogger().info(name + " executed");
    } catch (final Error error) {
        getLogger().severe(name + " failed: " + error.getMessage());
    }
}
```
    
> bookmetatest
getter executed
workingChain executed
setterL executed
setterL2 failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
setterA executed
setterA2 failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
doubleSetter failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
doubleSetter2 failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
title executed
title2 failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
author executed
author2 failed: Class org.bukkit.craftbukkit.inventory.CraftMetaBookSigned does not implement the requested interface net.kyori.adventure.inventory.Book
Executed book meta test
</details>

**Comment by masmc05** [comment]
Yeah those are harder to fix, that's why in the original issue I mentioned redirecting instead the calls to an internal class with static methods that take the book meta + the arguments and returns an adventure book, this way nothing further should be affected as it's continuing to expect the Book instance

**Comment by TheosRee** [comment]
Your suggestion works like a charm!
All test calls now work, however any call after the first page just creates a new book and does not modify the Meta anymore, but who would do that anyway? Right?

**Comment by masmc05** [comment]
In my opinion that is fine, lots of deprecated methods become no-op in new version releases without a warning period (and this one had a bit of warning period), while the plugin at least loads. But better wait for a team member to decide

**Comment by TheosRee** [comment]
I would also like if I should put another fix for the WritableBookMeta storing the pages as legacy string and converting them leads to that components or if I should put all changes to the Craft classes into a separate PR:


grafik


Edit: Looking a bit longer into internals it looks on purpose that components don't work great in there.

<details>
<summary>Code</summary>

```java
final Component deserialized = MiniMessage.miniMessage().deserialize("<rainbow><bold>Really");
for (final Material material : new Material[]{Material.WRITTEN_BOOK, Material.WRITABLE_BOOK}) {
    final ItemStack book = ItemStack.of(material);
    final BookMeta bookMeta = (BookMeta) book.getItemMeta();
    bookMeta.title(deserialized).author(deserialized).pages(deserialized);
    book.setItemMeta(bookMeta);
    player.give(book);
}
</details>

**Comment by electronicboy** [comment]
if that breakage isn't related to this then a separate PR is preferred, prevents one thing blocking the other needlessly

**Review by kennytv — DISMISSED** [review]
The two Craft* changes don't belong here, but the commodore changes look reasonable

**Comment by TheosRee** [comment]
> The two Craft* changes don't belong here, but the commodore changes look reasonable

As already wrote to mbax in the DC I made these changes to retain the behavior to before the adventure 5 change. After that the Writable Book no longer had colorful pages and the WrittenBook no longer had neither title nor author.

For that reason I see that as required part of the fix to maintain backwards compatibility/have consistent behavior.

Edit: Also, with that comment being an approve and not a change request I thought of it more of a "well, it should not be here but I guess I don't care enough".

**Comment by TheosRee** [comment]
On suggestion of @masmc05 I added a second issue with reasoning for the Craft changes done in this PR and edited the description.

**Comment by TheosRee** [comment]
@kennytv do you think that is a thing that should be merged in 26.2 so the latest release does not have this issue?
I just realized you can add pages with using the `addPages` method but replacing is not possible for plugins compiled to older versions.
