### ISSUE TITLE
Player#setLevel broken in PlayerRespawnEvent

### ISSUE THREAD

**Issue by kangarko** [PaperMC/Paper#1266]
![a](https://i.imgur.com/k3tMsfT.png)

The above code does not work without the BukkitRunnable clause, i.e. just calling Player.setLevel won't do anything (same for the health). Tried different priorities, all seem broken. 

Also, delaying it by 1 tick in reality gives the exp bar after 1 seconds or so (over 20 ticks from my subjective experience on a localhost test server with 0 lag).

This is critical when restoring back a player's inventory after he died and is respawned (i.e. when a minigame ends, see, https://github.com/kangarko/CoreArena/issues/69). 

If that's not a bug, please navigate me to do it properly.

### Plugin list:
Just my testing plugin.

### Paper build number:
1511

**Comment by aikar** [comment]
Does this behave differently on Spigot?
I think this is expected behavior. After death, experience is set to be applied at 'next tick of being alive'

You may need to delay your code 2 ticks.

Can you not use the death event for this?

**Comment by kangarko** [comment]
No I cannot use death event.

Alright, will delay to 2 ticks. Is this entire code safe to be delay (synchronously)?

````java
final StoredInventory s = getStored(pl);
Validate.isTrue(s != null, "Player " + pl.getName() + " does not have a stored inventory!");

pl.setGameMode(s.getGameMode());

pl.getInventory().setArmorContents(s.getArmorContent());
pl.getInventory().setContents(s.getContent());

try {
	pl.getInventory().setExtraContents(s.getExtraContent());
} catch (final NoSuchMethodError err) {}

pl.setMaxHealth(s.getMaxHealth());
pl.setHealth(s.getHealth());
pl.setHealthScaled(s.isHealthScaled());

pl.setRemainingAir(s.getRemainingAir());
pl.setMaximumAir(s.getMaximumAir());
pl.setFallDistance(s.getFallDistance());
pl.setFireTicks(s.getFireTicks());

pl.setTotalExperience(s.getTotalXp());
pl.setExp(s.getExp());
pl.setLevel(s.getLvl());

pl.setFoodLevel(s.getFoodLevel());
pl.setExhaustion(s.getExhaustion());
pl.setSaturation(s.getSaturation());

pl.setFlySpeed(s.getFlySpeed());
pl.setWalkSpeed(s.getWalkSpeed());

try {
	pl.setGlowing(s.isGlowing());
	pl.setInvulnerable(s.isInvulnerable());
	pl.setSilent(s.isSilent());
} catch (final NoSuchMethodError err) {}

// Potions
for (final PotionEffect ef : pl.getActivePotionEffects())
	pl.removePotionEffect(ef.getType());

for (final PotionEffect ef : s.getPotionEffects())
	pl.addPotionEffect(ef);

// Scoreboard tags
try {
	for (final String tag : s.getScoreboardTags())
		pl.addScoreboardTag(tag);
} catch (final Throwable err) {}
````

**Comment by aikar** [comment]
You nevet let me know, does the code function in spigot - or are you just mainly asking for help to get this to work?
all api's are 'safe' to run on main concurrency wise, now whether or not its slow is a different question i cant answer.

but if your modifying the players data, it needs to be on main

**Comment by electronicboy** [comment]
CB calls reset on EntityPlayer right after that event is fired, which sets the players exp level back to 0 unless they have keepLevel/keepInventory set

**Comment by kangarko** [comment]
@aikar apologies for not letting you know, yes, calling Player#setLevel without a Runnable does work fine on pure Spigot version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2)

![https://i.imgur.com/Wae4g0m.gif](https://i.imgur.com/Wae4g0m.gif)

**Comment by jiongjionger** [comment]
try
p.setExp(0.0F);
p.setLevel(0);
p.setTotalExperience(0);
p.giveExp(newExp);

**Comment by kangarko** [comment]
I workaround with a Runnable for the time being, closing so you can prioritize other major issues or work on 1.13.
