### ISSUE TITLE
NoSuchMethodError for (removed adventure) Book interface's setter

### ISSUE THREAD

**Issue by TheosRee** [PaperMC/Paper#14030]
### Expected behavior

When compiling against Paper 26.1.2 (or before) using the BookMeta#pages setter methods should also work on a 26.2 server since it is api.

### Observed/Actual behavior

[17:35:25 INFO]: TheosRee issued server command: /bookmetatest getter
[17:35:29 INFO]: TheosRee issued server command: /bookmetatest setterArray
[17:35:29 ERROR]: Command exception: /bookmetatest setterArray
java.lang.NoSuchMethodError: 'net.kyori.adventure.inventory.Book org.bukkit.inventory.meta.BookMeta.pages(net.kyori.adventure.text.Component[])'
        at TR-Test.jar//de.ree.theos.Test$1.execute(Test.java:69) ~[?:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-26.2.jar:26.2-20-2c0341f]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-26.2.jar:26.2-20-2c0341f]
[…more stack trace]
[17:35:33 INFO]: TheosRee issued server command: /bookmetatest setterList
[17:35:33 ERROR]: Command exception: /bookmetatest setterList
java.lang.NoSuchMethodError: 'net.kyori.adventure.inventory.Book org.bukkit.inventory.meta.BookMeta.pages(java.util.List)'
        at TR-Test.jar//de.ree.theos.Test$1.execute(Test.java:68) ~[?:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-26.2.jar:26.2-20-2c0341f]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-26.2.jar:26.2-20-2c0341f]
[…more stack trace]

### Steps/models to reproduce

```java
getServer().getCommandMap().register("ignored", new Command("bookmetatest") {
    @Override
    public boolean execute(final CommandSender sender, final String label, final String[] args) {
        final ItemStack book = ItemStack.of(Material.WRITTEN_BOOK);
        final BookMeta meta = (BookMeta) book.getItemMeta();
        switch (args[0]) {
            case "getter" -> meta.pages();
            case "setterList" -> meta.pages(List.of());
            case "setterArray" -> meta.pages(Component.empty());
        }
        return true;
    }
});
```

targetting the following version or any before down to like 1.18
```xml
<dependency>
    <groupId>io.papermc.paper</groupId>
    <artifactId>paper-api</artifactId>
    <version>26.1.2.build.72.stable</version>
    <scope>provided</scope>
</dependency>
```

### Plugin and Datapack List

The test plugin

### Paper version

This server is running Paper version 26.2-20-dev/26.2@2c0341f (2026-06-17T19:31:24Z) (Implementing API version 26.2.build.20-alpha)
You are 28 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 26.2-19-80d1098 (MC: 26.2)

This server is running Paper version 26.2-48-main@87c4d42 (2026-07-04T14:09:05Z) (Implementing API version 26.2.build.48-alpha)
You are running the latest version
Previous version: 26.2-20-2c0341f (MC: 26.2)

### Other

it is since https://fill-ui.papermc.io/projects/paper/version/26.2?build=20 with
https://github.com/PaperMC/Paper/commit/2c0341f9f291cba995c5293122bf888138427d17#diff-e0871225f23971b54756b88cbe0d16e1aa4995d857a5d0c56aa7c18e904f647eL17-R20
I asked on Discord and it was suggested to open the issue in Paper instead Adventure because it is an Item-/BookMeta issue and should probably get an `api-version` rewrite.

**Comment by Doc94** [comment]
Well feel expected.. in 26.1 the whole BookMeta has a mention for
> Warning: in an upcoming version of Paper, this interface will no longer extend Adventure's net.kyori.adventure.inventory.Book

and that pages() method comes from the adventure Book, in 26.2 with the upgrade of Adventure a new method was added but that method return BookMeta and not Book like in the Adventure Book class... so not really sure if this is a thing can be fixed in a nice way because in that case you dont use the return value but in other cases this can happen and cause the same error...

**Comment by lynxplay** [comment]
Should probably be rewritten via bytecode for plugins using plugin.yml

**Comment by masmc05** [comment]
> in 26.1 the whole BookMeta has a mention for

The mention existed for too short amount of time for this level of breakage, such api changes must also be handled by bytecode rewrite (like commodore)

> and that pages() method comes from the adventure Book

The signature as shown in the error is on book meta so it shouldn't be hard to swap with an internal static book meta + List -> Book method

**Comment by TheosRee** [comment]
I've also read in the release of Adventure 5.0 that there should be no breaking changes and assumed with that it should also be the case for the platform implementations, even when the Book interface just got removed.

And well, the deprecation and removing was in just like 2 weeks, this is not really a huge timeframe ^^

Last to the chaining of methods, they can easily be changed to just not chain on older versions, so that is not really a problem.

**Comment by hiSandog** [comment]
A useful next step might be to separate the repro into input, state/cache update, and final output for `api-version`. That would make it clearer whether “NoSuchMethodError for (removed adventure) Book interface's setter” is failing during parsing/configuration, during internal state updates, or only at the user-visible result.

**Comment by masmc05** [comment]
@hiSandog not so sure how that is related to this issue, do you mean make some sort auto detection of such stuff for the future etc?
