### PR TITLE
Fix plugin loggers on shutdown

### LINKED ISSUE #5270: Disable plugins when shutting down server using SIGTERM/SIGINT
**Is your feature request related to a problem? Please describe.**
When sending `SIGTERM` or `SIGINT` to the PaperMC process, the server shuts down gracefully but without disabling plugins as would happen using the /stop command.

**Describe the solution you'd like**
Have one signal that behaves exactly as the /stop command to avoid using screen, RCON or similar workarounds.
As both `SIGTERM` and `SIGINT` have the same behavior, `SIGTERM` could be left as it is and `SIGINT` could be the one implementing this feature.

**Describe alternatives you've considered**
- Using RCON to send the /stop command.
- Typing "stop" in the stdin of the PaperMC process (e.g. using screen).

**Additional context**
Shutdown log using SIGTERM/SIGINT:
```
[21:05:46] [Server thread/INFO]: Stopping server
[21:05:46] [Server thread/INFO]: Saving players
[21:05:46] [Server thread/INFO]: Saving worlds
[21:05:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:05:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:05:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[21:05:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:05:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[21:05:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:05:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:05:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:05:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:05:47] [Server thread/INFO]: Flushing Chunk IO
[21:05:47] [Server thread/INFO]: Closing Thread Pool
[21:05:47] [Server thread/INFO]: Closing Server
```

Shutdown log using the /stop command:
```diff
+ [21:32:58] [Server thread/INFO]: Stopping the server
  [21:32:58] [Server thread/INFO]: Stopping server
+ [21:32:58] [Server thread/INFO]: [YamipaPlugin] Disabling YamipaPlugin v1.0.2
+ [21:32:58] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.6.0
+ [21:32:58] [Server thread/INFO]: [GroupManager] Disabling GroupManager v2.9 (Phoenix)
+ [21:32:58] [Server thread/WARN]: [GroupManager] Scheduled Data Saving is Disabled!
+ [21:32:58] [Server thread/INFO]: [GroupManager] version 2.9 (Phoenix) is disabled!
+ [21:32:58] [Server thread/INFO]: [ChestsPlusPlus] Disabling ChestsPlusPlus v2.3.1-Release
+ [21:32:59] [Server thread/INFO]: [Skript] Disabling Skript v2.5.3
+ [21:32:59] [Server thread/INFO]: [BetterSleeping3] Disabling BetterSleeping3 v3.0.4
+ [21:32:59] [Server thread/INFO]: [BottledExp] Disabling BottledExp v2.2.8.2
+ [21:32:59] [Server thread/INFO]: [BottledExp] You are no longer able to fill XP into Bottles
  [21:32:59] [Server thread/INFO]: Saving players
  [21:32:59] [Server thread/INFO]: Saving worlds
  [21:32:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
  [21:32:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
  [21:32:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
  [21:32:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
  [21:32:59] [Server thread/INFO]: Flushing Chunk IO
  [21:32:59] [Server thread/INFO]: Closing Thread Pool
  [21:32:59] [Server thread/INFO]: Closing Server
```

### PR DESCRIPTION
**Pull request by josemmo**
- Added stop signal listener to MinecraftServer
- Fixes #5270

> When system property "terminal.jline" is false and the server receives a SIGINT/SIGTERM plugin, non-root loggers did not work due to how shutdown hooks work.

### CODE REVIEW

**Review by Proximyst — COMMENTED** [review]
```
warning: sun.misc.SignalHandler is Sun proprietary API and may be removed in a future release
```

Dunno if we want to rely on this...

**Review by electronicboy — APPROVED** [review]

**Comment by electronicboy** [comment]
that API has been around for a loooong time, I can't really see something getting rid of it on the basis that it's the only way to actually hook into these signals afaik, I can't see this getting stripped out any time soon

**Comment by electronicboy** [comment]
I'm assuming that you've tested that this doesn't bork anything when ran with/without jline?

**Comment by Shevchik** [comment]
The attempt to init signal handler should be wrapped in try-catch then, just in case.

File: Spigot-Server-Patches/0723-Fix-plugin-loggers-on-server-shutdown.patch [hunk 1]
```diff
@@ -0,0 +1,27 @@
+From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
+From: =?UTF-8?q?Jos=C3=A9=20Miguel=20Moreno?= <josemmo@pm.me>
```
Comment (HexedHero) [inline Spigot-Server-Patches/0723-Fix-plugin-loggers-on-server-shutdown.patch]: The hell is this author-name

Comment (zml2008) [reply Spigot-Server-Patches/0723-Fix-plugin-loggers-on-server-shutdown.patch]: https://en.wikipedia.org/wiki/MIME#Encoded-Word

**Comment by josemmo** [comment]
> @electronicboy
> I'm assuming that you've tested that this doesn't bork anything when ran with/without jline?

Tested on Java 8 with ` nogui` (JLine enabled) and ` --nojline nogui` (JLine disabled), and stopping server using the /stop command and sending CTRL+C keyboard combination.

With JLine enabled the stop signal handler doesn't get called as JLine intercepts the program input.

---

> @electronicboy
> that API has been around for a loooong time, I can't really see something getting rid of it on the basis that it's the only way to actually hook into these signals afaik, I can't see this getting stripped out any time soon

Just created a simple project with JDK 16 and "sun.misc.\*" is still there. It is also available in the internal "[jdk.internal.misc.\*](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8149750)" package. In the wost case scenario this package can be exposed with `--add-exports`.

---

> @Proximyst
> Dunno if we want to rely on this...

If hooking into internal APIs is an issue the other alternative is to hijack the app log manager and override the  `reset()` method, which is the one responsible for loggers not working on shutdown:
```java
System.setProperty("java.util.logging.manager", CustomLogManager.class.getName());

public static class CustomLogManager extends LogManager {
    // [...]
    @Override
    public void reset() {
        // Ignore method call if still shutting down
        // [...]
    }
}
```

**Comment by kashike** [comment]
Ref: https://openjdk.java.net/jeps/260

**Comment by A248** [comment]
> warning: sun.misc.SignalHandler is Sun proprietary API and may be removed in a future release

If there's a warning about it, that seems reason enough to avoid it. In JDK 16 there is also [Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396). Now is definitely not the time to regress back to depending on internals.

**Comment by josemmo** [comment]
Ok, I guess the consensus here is to avoid using signal handlers.
Should I update the PR to fix #5270 by hijacking the log manager then?

**Comment by josemmo** [comment]
Just pushed a new patch that uses the custom log manager approach instead of signal handlers.

**Review by electronicboy — APPROVED** [review]

File: Spigot-Server-Patches/0739-Fix-plugin-loggers-on-server-shutdown.patch [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+Subject: [PATCH] Fix plugin loggers on server shutdown
+
+
+diff --git a/src/main/java/com/destroystokyo/paper/log/CustomLogManager.java b/src/main/java/com/destroystokyo/paper/log/CustomLogManager.java
+new file mode 100644
+index 0000000000000000000000000000000000000000..cc9f5e3dd5a43c033a716675450c149be3e2d61d
+--- /dev/null
++++ b/src/main/java/com/destroystokyo/paper/log/CustomLogManager.java
+@@ -0,0 +1,26 @@
++package com.destroystokyo.paper.log;
```
Comment (Proximyst) [inline Spigot-Server-Patches/0739-Fix-plugin-loggers-on-server-shutdown.patch]: `io.papermc.paper.log`

**Review by Proximyst — APPROVED** [review]
Clean! Nice!

**Comment by josemmo** [comment]
Had to rebase due to a mistype... 🤦‍♂️
Anyway, the custom logger class FQN now is `io.papermc.paper.log.CustomLogManager`.

File: Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+index 409fbeeb66fb8f58a72d94686bc9515299927b75..3a7b3264eb240ed43640fdc0623b328afb14453c 100644
+--- a/src/main/java/org/bukkit/craftbukkit/Main.java
++++ b/src/main/java/org/bukkit/craftbukkit/Main.java
+@@ -20,6 +20,12 @@ public class Main {
+     public static boolean useJline = true;
+     public static boolean useConsole = true;
+ 
++    // Paper start - Hijack log manager to ensure logging on shutdown
++    static {
++        System.setProperty("java.util.logging.manager", io.papermc.paper.log.CustomLogManager.class.getName());
```
Comment (A248) [inline Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: Are you sure `CustomLogManager.class` won't accidentally initialize LogManager? If you init LogManager too early, setting the property will happen too late.

I trust if you say that this worked during your testing.

**Review by A248 — COMMENTED** [review]
More of a question than a comment.

File: Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch (hunk 3 above)
Comment (DenWav) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: I think this would be safest as string literal even if it does work - removes any possibly ambiguity.

**Review by Machine-Maker — CHANGES_REQUESTED** [review]

File: Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch (hunk 3 above)
Comment (josemmo) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: > Are you sure `CustomLogManager.class` won't accidentally initialize LogManager?

The "java.util.logging.manager" property is being set as soon as the Main class is loaded and AFAIK there's no other place in the source code where this property gets overwritten. Tested it and it works, can't think of any reason why it shouldn't.

> I think this would be safest as string literal even if it does work - removes any possibly ambiguity.

The reason I don't use a string literal is because the app will crash if it fails to resolve the FQN, an error that otherwise will go unnoticed.

Comment (Proximyst) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: If that's the case, I think using a string is fine. If it crashes when you rename it, you've obviously done something wrong. Put a comment in the class and I'm sure it's all good.

Comment (josemmo) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: Ok, I'll change it. But bear in mind if someone refactors CustomLogManager their IDE will not recognize the string literal as a FQN and will not rename it.

File: Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
++}
+diff --git a/src/main/java/net/minecraft/server/MinecraftServer.java b/src/main/java/net/minecraft/server/MinecraftServer.java
+index bf80e870e6a2a6fe1d4ae1bea355bcd7a0735d3b..9bbad437983d406ceb285ad2a431a653b270a73b 100644
+--- a/src/main/java/net/minecraft/server/MinecraftServer.java
++++ b/src/main/java/net/minecraft/server/MinecraftServer.java
+@@ -14,6 +14,7 @@ import io.netty.buffer.ByteBufOutputStream;
+ import io.netty.buffer.Unpooled;
+ import io.papermc.paper.adventure.PaperAdventure; // Paper
+ import io.papermc.paper.event.entity.EntityMoveEvent;
++import io.papermc.paper.log.CustomLogManager;
```
Comment (Machine-Maker) [inline Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: Don't import here, use FQN below

**Review by Machine-Maker — DISMISSED** [review]

File: Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch (hunk 4 above)
Comment (josemmo) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: I don't know whether that's possible. When using FQN instead of an import I get the following error trying to package the Paper-Server module:
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project paper: Compilation failure
/home/josemmo/PaperMC/Paper-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[973,11] cannot find symbol
  symbol:   variable papermc
  location: class net.minecraft.server.io
```

Besides, all other `io.papermc.*` classes used in `net.minecraft.server.MinecraftServer` have an import statement.

Comment (electronicboy) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: Fully qualified in 1.16.5 won't work because of the ever loving `io` class, this will work fine in 1.17

Comment (josemmo) [reply Spigot-Server-Patches/0755-Fix-plugin-loggers-on-server-shutdown.patch]: Is there any documentation on how to build Paper 1.17? I'm trying to rebase this branch and can't even apply patches to master at commit 98fa13609982b3ee19928efed96f4d23735ea100:

```
> Task :patchCraftBukkitPatches FAILED
error: patch failed: .gradle/caches/paperweight/taskCache/patchCraftBukkitPatches.zip-1711287088/net/minecraft/world/entity/ai/behavior/BehaviorWorkComposter.patch:1
error: .gradle/caches/paperweight/taskCache/patchCraftBukkitPatches.zip-1711287088/net/minecraft/world/entity/ai/behavior/BehaviorWorkComposter.patch: patch does not apply        
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':patchCraftBukkitPatches'.
> io.papermc.paperweight.PaperweightException: Command finished with 1 exit code: git -c commit.gpgsign=false -c core.safecrlf=false apply C:\Users\josemmo\Desktop\PaperMC\build-data\craftbukkit-patch-patches\BehaviorWorkComposter.patch.patch
```

The failing git command prints the following error message:
```
error: net/minecraft/world/entity/ai/behavior/BehaviorWorkComposter.patch: No such file or directory
```

**Comment by AwesomeDude091** [comment]
Could this be looked at again?
